version: 2

defaults: &defaults
    working_directory: /sources # directory where steps will run
    environment:
      RPMLINT: 1
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: "Prepare Kodi tarball"
          command: ./kodi-generate-tarball-xz.sh
      - run:
          name: "Get external libs for DVD"
          command: |
            wget -O kodi-libdvdnav-6.0.0-Leia-Alpha-3.tar.gz https://github.com/xbmc/libdvdnav/archive/6.0.0-Leia-Alpha-3.tar.gz
            wget -O kodi-libdvdread-6.0.0-Leia-Alpha-3.tar.gz https://github.com/xbmc/libdvdread/archive/6.0.0-Leia-Alpha-3.tar.gz
            wget -O kodi-libdvdcss-1.4.2-Leia-Beta-5.tar.gz https://github.com/xbmc/libdvdcss/archive/1.4.2-Leia-Beta-5.tar.gz
      - run:
          name: "Ensure RPMFusion"
          command: dnf -y install https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm
      - run:
          name: "Run the build itself: this will do rpmlint and check RPMs existence among other things."
          command: build
      - persist_to_workspace:
          root: /output
          paths:
            - "*.rpm"
deploy: &deploy
  docker:
    - image: kroniak/ssh-client
  working_directory: /output
  steps:
    - attach_workspace:
        at: /output
    - add_ssh_keys:
        fingerprints:
          - "8c:a4:dd:2c:47:4c:63:aa:90:0b:e0:d6:15:be:87:82"
    - run:
        name: "Ensure project specific upload directory to avoid deploy collisions"
        command: >
          ssh -o StrictHostKeyChecking=no
          $GPS_BUILD_USER@$GPS_BUILD_SERVER
          "mkdir -p ~/incoming/$CIRCLE_PROJECT_REPONAME/$DISTRO"
    - run:
        name: "Deploy all RPMs to GetPageSpeed repo."
        command: >
          scp -o StrictHostKeyChecking=no -q -r *.rpm
          $GPS_BUILD_USER@$GPS_BUILD_SERVER:~/incoming/$CIRCLE_PROJECT_REPONAME/$DISTRO/
    - run:
        name: "Trigger Deploy Hook."
        command: >
          ssh -o StrictHostKeyChecking=no -q
          $GPS_BUILD_USER@$GPS_BUILD_SERVER
          "nohup ~/scripts/incoming.sh $CIRCLE_PROJECT_REPONAME/$DISTRO > ~/incoming/$CIRCLE_PROJECT_REPONAME/$DISTRO/process.log 2>&1&"
jobs: # a collection of steps
  el8:
    docker:
      - image: getpagespeed/rpmbuilder:centos-8
    <<: *defaults
  deploy-el8:
    <<: *deploy
    environment:
      DISTRO: el8
workflows:
  version: 2
  build-deploy-el8:
    jobs:
      - el8
      - deploy-el8:
          context: org-global
          requires:
            - el8
          filters:
            branches:
              only: master